version: "3"

services:
    blog-front:
        container_name: blog-front
        build:
            context: .
            dockerfile: ./apps/blog/Dockerfile
        restart: unless-stopped
        ports:
            - 4200:3000
        networks:
            - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
    app_network:
        external: true
