version: "3"

services:
    blog-front-blue: &front
        container_name: blog-front-blue
        build:
            context: .
            dockerfile: ./apps/blog/Dockerfile
        restart: unless-stopped
        ports:
            - 4200:3000
        networks:
            - app_network
        environment:
            TZ: "Asia/Seoul"
    blog-front-green:
        <<: *front
        container_name: blog-front-green
        ports:
            - 4201:3000

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
    app_network:
        external: true
