const icons = [
    "alternate-email",
    "arrow-downward",
    "arrow-outward",
    "autorenew",
    "build",
    "call",
    "category",
    "chat-bubble",
    "chevron-left",
    "chevron-right",
    "code-blocks",
    "code",
    "construction",
    "deployed-code",
    "edit",
    "file-copy",
    "forum",
    "home",
    "image",
    "info",
    "language",
    "lightbulb",
    "link",
    "list",
    "local-shipping",
    "lock-open-right",
    "lock",
    "mail",
    "memory",
    "note",
    "notifications",
    "open-in-new",
    "package",
    "palette",
    "photo-camera",
    "send",
    "share",
    "tag",
    "warning",
    "work",
] as const;

export default icons;
