name: Check PR

on:
    pull_request:

env:
    CI: true

jobs:
    visual-regression-test:
        name: Run visual regression test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/setup-pnpm@master
            - uses: dtinth/setup-github-actions-caching-for-turbo@v1
            - name: Install puppeteer
              run: npx puppeteer browsers install chrome
            - name: Run backstop server in background
              run: pnpm dev --filter @marshallku/visual-regression &
            - name: Build apps and packages without blog
              run: pnpm build --filter !@marshallku/blog
            - name: Run test
              id: test
              continue-on-error: true
              run: pnpm test:visual-regression
            - name: Check test result
              if: ${{ !cancelled() }}
              uses: thollander/actions-comment-pull-request@v2
              with:
                  message: |
                      Test result - ${{ steps.test.outcome }}

                      You can check results [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            - name: Upload test results
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: backstop-data
                  path: apps/visual-regression/backstop_data
                  retention-days: 30
