name: CI

on:
    push:

env:
    CI: true
    TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
    check-spelling:
        name: Check spelling
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/check-spelling@master
    lint-all:
        name: Check quality with ESLint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/setup-pnpm@master
            - name: Check code quality
              run: pnpm lint
    build-all:
        name: Build all packages and apps
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/setup-pnpm@master
            - name: Build apps and packages
              run: pnpm build
    test-blog-e2e:
        name: Run e2e test in blog
        needs: [build-all]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/setup-pnpm@master
            - name: Setup playwright
              run: |
                  cd apps/blog
                  pnpm exec playwright install
            - name: Build applications
              run: pnpm build
            - name: Run test
              run: pnpm test:e2e --filter @marshallku/blog
    lighthouse:
        name: Lighthouse CI
        needs: [build-all]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/setup-pnpm@master
            - name: Build app
              run: |
                  cp apps/blog/.env.example apps/blog/.env
                  pnpm build --filter @marshallku/blog
                  if [ -d apps/blog/.next/static ]; then cp -r apps/blog/.next/static apps/blog/.next/standalone/apps/blog/.next; fi
                  if [ -d apps/blog/public ]; then cp -r apps/blog/public apps/blog/.next/standalone/apps/blog/; fi
            - name: Run Lighthouse CI
              env:
                  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
              run: |
                  cd apps/blog
                  npm i -g @lhci/cli
                  lhci autorun
    send-notification:
        needs: [check-spelling, lint-all, build-all, test-blog-e2e, lighthouse]
        if: ${{ failure() }}
        uses: marshallku/actions/.github/workflows/send-notification.yml@master
        with:
            failed: ${{ contains(join(needs.*.result, ','), 'failure') }}
            message: "CI job failed"
        secrets:
            url: ${{ secrets.DISCORD_WEBHOOK_URI }}
