name: CI

on:
    push:

env:
    CI: true
    TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
    check-spelling:
        name: Check spelling
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/check-spelling@master
    lint-all:
        name: Check quality with ESLint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/setup-pnpm@master
            - name: Check code quality
              run: pnpm lint
    build-all:
        name: Build all packages and apps
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/setup-pnpm@master
            - name: Build apps and packages
              run: pnpm build
    test-all:
        name: Build all packages and apps
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/setup-pnpm@master
            - name: Build apps and packages
              run: |
                  # setup playwright
                  cd apps/blog
                  pnpm exec playwright install 
                  cd ../..

                  # run tests
                  pnpm test
    lighthouse:
        name: Lighthouse CI
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/setup-pnpm@master
            - name: Build app
              run: |
                  cp apps/blog/.env.example apps/blog/.env
                  pnpm build --filter @marshallku/blog
                  cp apps/blog/.next/static apps/blog/.next/standalone/apps/blog/.next -r
                  cp apps/blog/public apps/blog/.next/standalone/apps/blog/ -r
            - name: Run Lighthouse CI
              env:
                  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
              run: |
                  cd apps/blog
                  npm i -g @lhci/cli
                  lhci autorun
    send-notification:
        needs: [check-spelling, lint-all, build-all, test-all, lighthouse]
        if: ${{ failure() }}
        uses: marshallku/actions/.github/workflows/send-notification.yml@master
        with:
            failed: ${{ contains(join(needs.*.result, ','), 'failure') }}
            message: "CI job failed"
        secrets:
            url: ${{ secrets.DISCORD_WEBHOOK_URI }}
