name: CI / Push

on:
    push:

env:
    CI: true

jobs:
    check-spelling:
        name: Check spelling
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/check-spelling@master
    lint-all:
        name: Check quality with ESLint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/setup-pnpm@master
            - name: Check code quality
              run: pnpm lint
    build-all:
        name: Build all packages and apps
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/setup-pnpm@master
            - name: Build apps and packages
              run: pnpm build
    lighthouse:
        name: Lighthouse CI
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/setup-pnpm@master
            - name: Run Lighthouse CI
              env:
                  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
              run: |
                  pnpm build --filter @marshallku/blog
                  cd apps/blog
                  npm i -g @lhci/cli
                  lhci autorun
    send-notification:
        needs: [check-spelling, lint-all, build-all, lighthouse]
        if: ${{ failure() }}
        uses: marshallku/actions/.github/workflows/send-notification.yml@master
        with:
            failed: ${{ contains(join(needs.*.result, ','), 'failure') }}
            message: "CI job failed - push on master"
        secrets:
            url: ${{ secrets.DISCORD_WEBHOOK_URI }}
