name: CI

on:
    push:

env:
    CI: true

jobs:
    check-spelling:
        name: Check spelling
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/check-spelling@master
    build-and-lint:
        name: Build all packages and apps, and check quality with ESLint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/setup-pnpm@master
            - name: Build apps and packages
              run: pnpm build
            - name: Check code quality
              run: pnpm lint
    test-blog-e2e:
        name: Run e2e test in blog
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/setup-pnpm@master
            - name: Setup playwright
              run: pnpm exec playwright install --with-deps
            - name: Build applications
              run: pnpm build
            - name: Run test
              run: pnpm test:e2e --filter @marshallku/blog
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: apps/blog/test-results/
                  retention-days: 30
    lighthouse:
        name: Lighthouse CI
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/setup-pnpm@master
            - name: Build app
              run: |
                  cp apps/blog/.env.example apps/blog/.env
                  pnpm build --filter @marshallku/blog
                  if [ -d apps/blog/.next/static ]; then cp -r apps/blog/.next/static apps/blog/.next/standalone/apps/blog/.next; fi
                  if [ -d apps/blog/public ]; then cp -r apps/blog/public apps/blog/.next/standalone/apps/blog/; fi
            - name: Run Lighthouse CI
              env:
                  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
              run: |
                  cd apps/blog
                  npm i -g @lhci/cli
                  lhci autorun
    send-notification:
        needs: [check-spelling, build-and-lint, test-blog-e2e, lighthouse]
        if: ${{ failure() }}
        uses: marshallku/actions/.github/workflows/send-notification.yml@master
        with:
            failed: ${{ contains(join(needs.*.result, ','), 'failure') }}
            message: "CI job failed"
        secrets:
            url: ${{ secrets.DISCORD_WEBHOOK_URI }}
