name: CD - blog app

on:
    push:
        branches:
            - master
    workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: marshallku/marshallku-blog-frontend

jobs:
    push-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Checkout blog posts
              uses: actions/checkout@v4
              with:
                  repository: marshallku/marshallku-blog-posts
                  path: apps/blog/_posts
                  token: ${{ secrets.GH_TOKEN }}
            - name: TurboRepo server
              uses: felixmosh/turborepo-gh-artifacts@v3
              with:
                  repo-token: ${{ github.token }}
            - name: Setup pnpm
              uses: marshallku/actions/setup/pnpm@master

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Setup cache
              uses: actions/cache@v4
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=ref,event=branch
                      type=ref,event=pr
                      type=semver,pattern={{version}}

            - name: Add default tags
              run: echo "TAGS=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:nightly" >> $GITHUB_ENV

            - name: Overwrite version tags
              if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && steps.create-tag-release.outputs.tag-exists == 'false' }}
              run: echo "TAGS=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ steps.check.outputs.version }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_ENV

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
                  tags: ${{ env.TAGS }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
            - name: Move cache
              run: |
                  rm -rf /tmp/.buildx-cache
                  mv /tmp/.buildx-cache-new /tmp/.buildx-cache
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Run remote script
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_IP }}
                  port: ${{ secrets.SERVER_PORT }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.ED_KEY }}
                  script: /home/${{ secrets.SERVER_USER }}/dev/marshallku-blog-frontend/scripts/deploy.sh
    send-notification:
        needs: [deploy]
        if: ${{ failure() }}
        uses: marshallku/actions/.github/workflows/send-notification.yml@master
        with:
            failed: ${{ contains(join(needs.*.result, ','), 'failure') }}
            message: "CI job failed - push"
        secrets:
            url: ${{ secrets.DISCORD_WEBHOOK_URI }}
