name: Deploy frontend to server

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Run remote script
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_IP }}
                  port: ${{ secrets.SERVER_PORT }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.ED_KEY }}
                  script_stop: true
                  script: |
                      cd /var/www
                      ./deploy.sh gifconverter
