name: Visual Regression Test

on:
    push:
        branches:
            - master
    workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    test:
        name: Run visual regression test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/setup-pnpm@master
            - uses: dtinth/setup-github-actions-caching-for-turbo@v1
            - name: Install puppeteer
              run: npx puppeteer browsers install chrome
            - name: Run backstop server in background
              run: pnpm dev --filter @marshallku/visual-regression &
            - name: Build apps and packages without blog
              run: pnpm build --filter !@marshallku/blog
            - name: Run test
              id: test
              continue-on-error: true
              run: pnpm test:visual-regression
            - name: Check test result
              id: check-test-result
              run: |
                  OUTPUT=$(node apps/visual-regression/reportResult.js)
                  echo "$OUTPUT" >> "$GITHUB_ENV"
            - name: Create commit comment
              if: ${{ !cancelled() }}
              uses: peter-evans/commit-comment@v3
              with:
                  body: |
                      Visual regression test result - **${{ steps.test.outcome }}**

                      ${{ env.TEST_RESULT }}
            - name: Approve results
              if: ${{ steps.test.outcome == 'failure' }}
              run: |
                  cd apps/visual-regression
                  pnpm backstop:approve
            - name: Commit changes
              if: ${{ steps.test.outcome == 'failure' }}
              run: bash .github/scripts/commit.sh
              env:
                  MESSAGE: "Update visual regression test results"
