name: Visual Regression Test

on:
    pull_request:

env:
    CI: true
    TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
    test:
        name: Run visual regression test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: marshallku/actions/setup-pnpm@master
            - name: Install puppeteer
              run: npx puppeteer browsers install chrome
            - name: Build apps and packages without blog
              run: pnpm build --filter !@marshallku/blog
            - name: Run backstop server in background
              run: pnpm dev --filter @marshallku/visual-regression &
            - name: Generate reference files
              run: |
                  git checkout ${{ github.base_ref }}
                  cd apps/visual-regression
                  pnpm backstop:reference
                  cd ../..
            - name: Checkout to PR branch
              run: git checkout ${{ github.head_ref }}
            - uses: marshallku/actions/setup-pnpm@master
            - name: Build apps and packages without blog
              run: pnpm build --filter !@marshallku/blog
            - name: Run test
              run: pnpm test:visual-regression
            - name: Upload test results
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: backstop-data
                  path: apps/visual-regression/backstop_data
                  retention-days: 30
